// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwYY7RYcMWJXfGkrPk9-eHAgOVnjsQoBo',
    appId: '1:967411829407:web:0f76804c97633dcd2530aa',
    messagingSenderId: '967411829407',
    projectId: 'eapp-d46b2',
    authDomain: 'eapp-d46b2.firebaseapp.com',
    storageBucket: 'eapp-d46b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5CL3Vi1UjhuVDqK5eozfrRhQ-Y_Ltp58',
    appId: '1:967411829407:android:9c81c5fb3be30bb42530aa',
    messagingSenderId: '967411829407',
    projectId: 'eapp-d46b2',
    storageBucket: 'eapp-d46b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNwLUajJI7uIeYdA8UcOGV7jimnVmWDr4',
    appId: '1:967411829407:ios:a4aab88a8c7c3f7f2530aa',
    messagingSenderId: '967411829407',
    projectId: 'eapp-d46b2',
    storageBucket: 'eapp-d46b2.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNwLUajJI7uIeYdA8UcOGV7jimnVmWDr4',
    appId: '1:967411829407:ios:f9f1aea898f6a68a2530aa',
    messagingSenderId: '967411829407',
    projectId: 'eapp-d46b2',
    storageBucket: 'eapp-d46b2.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
